services:
  - type: web
    name: climate-risk-rwanda
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 dashboards.App:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENWEATHER_API_KEY
        value: c45952d88bbd1eae279947148383f7d6
      - key: FLASK_ENV
        value: production
